language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t puukko/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true puukko/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-north-1-550115197411"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY